<?php
/*
 * Message
 */
define("ERROR_LOGIN", "Login Gagal. Username anda tidak terdaftar atau password salah..." );
define("PROFILE_SAVE_SUCCESS", 'Profile berhasil disimpan ke database' );
define("PASSWORD_SAVE_SUCCESS", 'Password berhasil diganti' );
define("KATEGORI_SAVE_SUCCESS", 'Kategori berhasil disimpan ke database' );
define("KATEGORI_DELETE_SUCCESS", 'Kategori berhasil dihapus dari database' );
define("PORECEIVE_SAVE_SUCCESS", 'Penerimaan PO berhasil disimpan ke database' );
define("PORECEIVE_DELETE_SUCCESS", 'Penerimaan PO berhasil dihapus dari database' );
define("SEASON_SAVE_SUCCESS", 'Season berhasil disimpan ke database' );
define("SEASON_DELETE_SUCCESS", 'Season berhasil dihapus dari database' );
define("ARTIKELCONFIG_SAVE_SUCCESS", 'Artikel Config berhasil disimpan ke database' );
define("ARTIKELCONFIG_DELETE_SUCCESS", 'Artikel Config berhasil dihapus dari database' );

/*
 * General Message
 */
define("EXIST", " sudah ada didatabase" );
define("NOTFOUND", " Tidak ditemukan didatabase" );
define("USEDBY", " digunakan oleh " );
define("FAILSAVING", " Gagal disimpan ke database" );
define("FAILDELETING", " Gagal dihapus dari database" );
define("FAILSAVINGPASSWORD", " Password user disimpan ke database" );
define("INFO_CHOOSEROWBEFOREREMOVE", "Anda harus memilih data yang akan dihapus" );
define("INFO_CHOOSEROWBEFOREREEDIT", "Anda harus memilih data yang akan diedit" );
define("CONFIRM_DELETE", "Anda Yakin akan menghapus " );

?>